# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('wsngr', ['internet', 'wifi'])
    module.includes = '.'
    module.source = [
        'model/wsngr.cc',
        'model/wsngr-state.cc',
        'helper/wsngr-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('wsngr')
    module_test.source = [
        'test/wsngr-test-suite.cc',
        ]
    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        module_test.source.extend([
        #    'test/wsngr-examples-test-suite.cc',
             ])

    headers = bld(features='ns3header')
    headers.module = 'wsngr'
    headers.source = [
        'model/wsngr.h',
        'model/wsngr-state.h',
        'helper/wsngr-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

